spring.application.name=developer-intelligence-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/developer_intelligence
spring.datasource.username=postgres
spring.datasource.password=kavya12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true